CREATE TABLE IF NOT EXISTS `DEPARTMENT` (
  `DEPARTMENTID` int(100) NOT NULL AUTO_INCREMENT,
  `DEPARTMENTCODE` varchar(10) NOT NULL,
  `DEPARTMENTNAME` varchar(20) NOT NULL,
    PRIMARY KEY (`DEPARTMENTID`),
     UNIQUE KEY `DEPARTMENT` (`DEPARTMENTCODE`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=5 ;

INSERT INTO  `DEPARTMENT` (`DEPARTMENTID`, `DEPARTMENTCODE`, `DEPARTMENTNAME`) VALUES
(1, 'ENG', 'Engineer'),
(2, 'TECNI', 'Technician'),
(3, 'SECANT', 'Secretary'),
(4, 'BA', 'Management');


