
CREATE TABLE IF NOT EXISTS `DEPARTMENTDETAIL` (
  `DEPARTMENTDETAILID` int(100) NOT NULL AUTO_INCREMENT,
  `DEPARTMENTID` int(100) NOT NULL,
  `DEPARTMENT_DETAIL_NAME` varchar(20) NOT NULL,
  `SALARY` INTEGER(20) NOT NULL,
    PRIMARY KEY (`DEPARTMENTDETAILID`),
    foreign key (DEPARTMENTID) references DEPARTMENT(DEPARTMENTID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=5 ;


INSERT INTO  `DEPARTMENTDETAIL` (`DEPARTMENTDETAILID`, `DEPARTMENTID`, `DEPARTMENT_DETAIL_NAME`,`SALARY`) VALUES
(1, 1, 'ElictricalEngineer',20000),
(2, 1, 'CivilEngineer',25000),
(3, 2, 'Carpenter',12000),
(4, 4, 'HightManagement',40000),
(5, 4, 'middletManagement',30000),
(6, 3, 'SecretaryBoss',300000);