CREATE TABLE IF NOT EXISTS `EXPORT_MATERIAL` (
  `EXPORT_MATERIALID` int(100) NOT NULL AUTO_INCREMENT,
  `EMPLOYEEID` int(100) NOT NULL,
  `REQUEST_MATERIALID` int(100) NOT NULL,
  `REQUEST_PROJECTID` int(100) NOT NULL,
  `EXPORT_MATERIALNO` varchar(6) NOT NULL,
  `EXPORT_DATE` date NOT NULL,
  `STATUS` varchar(20) NOT NULL,
  `TOTAL_EXPORT` int(50) NOT NULL,
   PRIMARY KEY (`EXPORT_MATERIALID`),
    foreign key (EMPLOYEEID) references EMPLOYEE(EMPLOYEEID)    
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;