CREATE TABLE IF NOT EXISTS `LOGIN` (
  `LGID` int(100) NOT NULL AUTO_INCREMENT,
  `LGUSERNAME` varchar(30) NOT NULL,
  `LGPASSWORD` varchar(20) NOT NULL,
  `LGROLEID` int(100) NOT NULL,
  `LGEMPLOYEEID` int(100) NOT NULL,
  `CREATE_USER` varchar(10) NOT NULL,
  `CREATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `UPDATE_USER` varchar(10) NOT NULL,
  `UPDATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`LGID`),
  UNIQUE KEY `LOGIN` (`LGUSERNAME`),
  UNIQUE KEY `LOGIN` (`LGEMPLOYEEID`),
  foreign key (LGROLEID) references ROLE(ROLEID),
  foreign key (LGEMPLOYEEID) references EMPLOYEE(EMPLOYEEID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;


INSERT INTO `LOGIN` (`LGID`, `LGUSERNAME`, `LGPASSWORD`, `LGROLEID`,`LGEMPLOYEEID` , `CREATE_USER`, `CREATE_DATE`, `UPDATE_USER`, `UPDATE_DATE`) VALUES
(1, 'admin', 'adminadmin',1,1, 'admin', '2015-08-06 10:41:47.245609', 'admin', '2015-08-06 10:41:47.245609');