CREATE TABLE IF NOT EXISTS `UNIT` (
  `UNITID` int(100) NOT NULL AUTO_INCREMENT,
  `UNITCODE` varchar(10) NOT NULL,
  `UNITNAME` varchar(20) NOT NULL,
  PRIMARY KEY (`UNITID`),
  UNIQUE KEY `UNIT` (`UNITCODE`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=8 ;

INSERT INTO `UNIT`( `UNITID`, `UNITCODE`,`UNITNAME`)VALUES
(1, 'P001', 'Piece'),(2, 'B002', 'Blade'),
(3, 'R003', 'Rods'),(4, 'RO004', 'Roll'),
(5, 'LO005', 'line'),(6, 'SO006', 'sheet'),
(7, 'TO006', 'Ton');