
CREATE TABLE IF NOT EXISTS `MATERIAL` (
  `MATERIALID` int(100) NOT NULL AUTO_INCREMENT,
  `MATERIALNAME` varchar(30) NOT NULL,
  `MATERIALCODE` varchar(5) NOT NULL,  
  `DESCRITION` varchar(255) NOT NULL,
  `PRICE` int (100)NOT NULL,
  `TYPEID` int(100)NOT NULL,
  `UNITID` int(100)NOT NULL,
  PRIMARY KEY (`MATERIALID`),
  UNIQUE KEY `MATERIAL` (`MATERIALNAME`),
 foreign key (TYPEID) references MATERIALTYPE(TYPEID), 
 foreign key (UNITID) references UNIT(UNITID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;

INSERT INTO `MATERIAL`  (`MATERIALID`,`MATERIALCODE`,`MATERIALNAME`,`DESCRITION`, `PRICE`, `TYPEID`, `UNITID`)VALUES
(1,'CCB','เเผ่นปูน','ตราห้าหวง',200,2,6),
(2,'CMM','เหล็ก','หนา ตรา ช้าง',400,1,5);






