
CREATE TABLE IF NOT EXISTS `MATERIAL` (
  `MATERIALID` int(100) NOT NULL AUTO_INCREMENT,
  `MATERIALNAME` varchar(30) NOT NULL,
  `MATERIALCODE` varchar(5) NOT NULL,  
  `DESCRIPTION` varchar(255) NOT NULL,
  `TYPEID` int(100)NOT NULL,
  `UNITID` int(100)NOT NULL,
  PRIMARY KEY (`MATERIALID`),
  UNIQUE KEY `MATERIAL` (`MATERIALNAME`),
 foreign key (TYPEID) references MATERIALTYPE(TYPEID), 
 foreign key (UNITID) references UNIT(UNITID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;

INSERT INTO `MATERIAL`  (`MATERIALID`,`MATERIALCODE`,`MATERIALNAME`,`DESCRIPTION`, `TYPEID`, `UNITID`)VALUES
(1,'CCB','เเผ่นปูน','ตราห้าหวง',2,6),
(2,'CMM','เหล็ก','หนา ตรา ช้าง',1,5);






