
CREATE TABLE IF NOT EXISTS `MATERIAL` (
  `MATERIALID` int(100) NOT NULL AUTO_INCREMENT,
  `MATERIALNAME` varchar(30) NOT NULL,
  `DESCRITION` varchar(50) NOT NULL,
  `PRICE` decimal(10,0),
  `TYPEID` int(100)NOT NULL,
  `UNITID` int(100)NOT NULL,
  PRIMARY KEY (`MATERIALID`),
  UNIQUE KEY `MATERIAL` (`MATERIALNAME`),
 foreign key (TYPEID) references MATERIALTYPE(TYPEID), 
 foreign key (UNITID) references UNIT(UNITID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=3 ;

INSERT INTO `MATERIAL`  (`MATERIALID`,`MATERIALNAME` ,`DESCRITION`, `PRICE`, `TYPEID`, `UNITID`)VALUES
(1,'เเผ่นปูน','ตราห้าหวง','200',2,6),
(2,'เหล็ก','หนา ตรา ช้าง','400',1,5);






