CREATE TABLE IF NOT EXISTS `MATERIALTYPE` (
  `TYPEID` int(100) NOT NULL AUTO_INCREMENT,
  `TYPECODE` varchar(10) NOT NULL,
  `TYPENAME` varchar(20) NOT NULL,
  PRIMARY KEY (`TYPEID`),
   UNIQUE KEY `MATERIALTYPE` (`TYPECODE`),
    UNIQUE KEY `TYPENAME` (`TYPENAME`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=5 ;

INSERT INTO `MATERIALTYPE`(  `TYPEID`,`TYPECODE`,`TYPENAME`  )VALUES
('1','1S-001' ,'Structure'),
('2','2F-002' ,'Flooring'),
('3','3W-003' ,'Wall'),
('4','4C-004' ,'Color'),
('5','5CE-005' ,'ceiling'),
('6','6R-006' ,'Roof');