CREATE TABLE IF NOT EXISTS `ORDER_MATERIALDETAIL` (
  `ORDER_MATERIALDETAIID` int(100) NOT NULL AUTO_INCREMENT,
  `ORDER_MATERIALID` int(100) NOT NULL,
  `MATERIALID` int(100) NOT NULL,
  `ANOTATION` varchar(20) NOT NULL,
  `QUANTITY_ORDER` int(30) NOT NULL,  
   PRIMARY KEY (`ORDER_MATERIALDETAIID`),
    foreign key (ORDER_MATERIALID) references EMPLOYEE(EMPLOYEEID), 
    foreign key (MATERIALID) references MATERIAL(MATERIALID)
    
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;