CREATE TABLE IF NOT EXISTS `ORDER_MATERIAL` (
  `ORDER_MATERIALID` int(100)  AUTO_INCREMENT,
  `EMPLOYEEID` int(100) NOT NULL,
  `ORDERMARERIAL_NO` varchar(225) NOT NULL,
  `ORDERMARERIAL_DATE` date NOT NULL,
   `STATUS` varchar(20) NOT NULL,
   `ADDRESS` varchar(50) NOT NULL,
  `CREATE_USER` varchar(10) NOT NULL,
  `CREATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  `UPDATE_USER` varchar(10) NOT NULL,
  `UPDATE_DATE` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),  
    PRIMARY KEY (`ORDER_MATERIALID`),
     foreign key (EMPLOYEEID) references EMPLOYEE(EMPLOYEEID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;