CREATE TABLE IF NOT EXISTS `RECEIVE_MATERIALDETAIL` (
  `RECEIVE_MATERIALDETAILID` int(100) NOT NULL AUTO_INCREMENT,
  `RECEIVEMATERIAL_ID` int(100) NOT NULL,
  `MATERIALID` int(100) NOT NULL,
  `RECEIVE_PRICE` int(100) NOT NULL,
  `RECEIVE_QUANTITY` int(100) NOT NULL,
   PRIMARY KEY (`RECEIVE_MATERIALDETAILID`),
    foreign key (MATERIALID) references MATERIAL(MATERIALID),
    foreign key (RECEIVEMATERIAL_ID) references RECEIVE_MATERIAL(RECEIVE_MATERIALID) 
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;