CREATE TABLE IF NOT EXISTS `RECEIVE_MATERIALDETAIL` (
  `RECEIVE_MATERIALDETAILID` int(100) NOT NULL AUTO_INCREMENT,
  `RECEIVE_MATERIALID` int(100) NOT NULL,
  `MATERAILID` int(100) NOT NULL,
  `RECEIVE_PRICE` int(100) NOT NULL,
  `RECEIVE_QUANTITY` int(100) NOT NULL,
   PRIMARY KEY (`RECEIVE_MATERIALDETAILID`),
    foreign key (MATERAILID) references MATERIAL(MATERIALID),
    foreign key (RECEIVE_MATERIALID) references RECEIVE_MATERIAL(RECEIVE_MATERIALID) 
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;