CREATE TABLE IF NOT EXISTS `REQUEST_MATERIAL` (
  `REQUEST_MATERIALID` int(100) NOT NULL AUTO_INCREMENT,
  `EMPLOYEEID` int(100) NOT NULL,
  `PROJECTID` int(100) NOT NULL,
  `REQUEST_MATERIALNO` varchar(6) NOT NULL,
  `CONTACT_OWNER` varchar(256) NOT NULL,
   `STATUS` varchar(20) NOT NULL,
  `REQUEST_DATE` date NOT NULL,
  `USE_MATERIALDATE` date NOT NULL,
   PRIMARY KEY (`REQUEST_MATERIALID`),
    foreign key (EMPLOYEEID) references EMPLOYEE(EMPLOYEEID) 
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;