CREATE TABLE IF NOT EXISTS `REQUEST_MATERIALDETAIL` (
  `REQUEST_MATERIALDETAIID` int(100) NOT NULL AUTO_INCREMENT,
  `REQUEST_MATERIALID` int(100) NOT NULL,
  `MATERIALID` int(100) NOT NULL,
  `QUANTITY_REQUEST` int(30) NOT NULL,  
   PRIMARY KEY (`REQUEST_MATERIALDETAIID`),
    foreign key (REQUEST_MATERIALID) references REQUEST_MATERIAL(REQUEST_MATERIALID), 
    foreign key (MATERIALID) references MATERIAL(MATERIALID)
    
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;