CREATE TABLE IF NOT EXISTS `STOCK` (
  `STOCKID` int(100) NOT NULL AUTO_INCREMENT,
  `MATERIALID` int(100) NOT NULL,
  `TOTAL_QUANTITY` int(50) NOT NULL,
    PRIMARY KEY (`STOCKID`),
   foreign key (MATERIALID) references MATERIAL(MATERIALID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

INSERT INTO `STOCK` (`STOCKID`, `MATERIALID`, `TOTAL_QUANTITY`) VALUES
(1, 1, 50);