CREATE TABLE IF NOT EXISTS `WORKING` (
  `WORKINGID` int(100) NOT NULL AUTO_INCREMENT,
  `EMPLOYEEID` int(100) NOT NULL ,
  `PROJECTID`   int(100) NOT NULL,
  `AMOUNT_MONTH`  integer(3)NOT NULL,
  `TOTAL_SALARY`  integer(100),
   PRIMARY KEY (`WORKINGID`),
   UNIQUE KEY `EMPLOYEEID` (`EMPLOYEEID`),
  foreign key (EMPLOYEEID) references EMPLOYEE(EMPLOYEEID),
  foreign key (PROJECTID) references PROJECT(PROJECTID)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8  AUTO_INCREMENT=1 ;



